### ISSUE TITLE
seccond step to of installation error

### ISSUE THREAD

**Issue by pizzapielordtemptest** [emilyst/hid-nx-dkms#20]
When entering 'dkms build hid-nx/1.14' into the terminal it gives me this error

Error! Your kernel headers for kernel 6.6.15-amd64 cannot be found at /lib/modules/6.6.15-amd64/build or /lib/modules/6.6.15-amd64/source.
Please install the linux-headers-6.6.15-amd64 package or use the --kernelsourcedir option to tell DKMS where it's located.

**Comment by emilyst** [comment]
Do you still get this error if you do as it suggests in the error message?

**Comment by pizzapielordtemptest** [comment]
I can't seem to find the package its referring to.

**Comment by emilyst** [comment]
It literally specifies which package to install in the error message.
