### ISSUE TITLE
[Request] LED patch

### ISSUE THREAD

**Issue by dmanlfc** [emilyst/hid-nx-dkms#4]
Hi Emily,

Can you include these patches in hid-nx?

It's worth noting the home LED patch is now set to be included in Linux 6.1:
https://github.com/torvalds/linux/commit/79d11de9637a37035b4a72ccb528b3dfebc1bf67
https://github.com/torvalds/linux/commit/8b30fb40f8f2c5e56b7af553a398340f92d17aae

Dan

**Comment by emilyst** [comment]
Thanks for the heads up on these. I'll try to do it soon.

**Comment by emilyst** [comment]
For my own reference, the actual patches from LKML:

* https://lore.kernel.org/all/20220415100432.23453-1-icenowy@aosc.io/
* https://lore.kernel.org/all/gvpL2G6VwXGJPvxX5KRiu9pVjvTivgayug_jdKDY6zfuAaAqncP9BkKLosjwUXNlgVVTMfJSKfwPF1K79cKAkwGComyC21vCV3q9B3EXNkE=@protonmail.com/

Links from GitHub:
* https://github.com/torvalds/linux/commit/50503e360eeb968a3d00234c9cc4057d774c3e9a
* https://github.com/torvalds/linux/commit/8b30fb40f8f2c5e56b7af553a398340f92d17aae

**Comment by emilyst** [comment]
Ported over changes from kernel and [released in v1.14](https://github.com/emilyst/hid-nx-dkms/releases/tag/v1.14). That should address this issue. Thanks again.

**Comment by dmanlfc** [comment]
Thanks 👍
